
export const ar = {
    "nav.talent": "انشئ سيرتك الذاتية",
    "nav.companies": "الشركات",
    "nav.features": "الميزات",
    "nav.faq": "الاسئلة الشائعة",
    "nav.login": "تسجيل الدخول",
    "nav.getStarted": "ابدأ الآن",
    "nav.hiring": "هل توظف؟",
    "nav.joinTalent": "انشئ سيرتك الذاتية",
    "nav.appearance": "المظهر",
    "nav.language": "اللغة",
    "nav.mode.dark": "داكن",
    "nav.mode.light": "فاتح",
    "nav.back": "رجوع",
    "nav.logout": "خروج",
    
    // Hero
    "hero.badge": "منشئ السيرة الذاتية الاحترافي",
    "hero.title.prefix": "سيرتك الذاتية..",
    "hero.title.highlight": "بوابتك الأولى نحو الوظيفة الحلم.",
    "hero.description": "أنشئ سيرة ذاتية احترافية ومجانية بالكامل خلال 5 دقائق فقط. صممت بمعايير عالمية لتجتاز أنظمة الفرز (ATS) وتلفت أنظار مسؤولي الموارد البشرية.",
    "hero.cta.find": "استكشف الوظائف المتاحة",
    "hero.cta.join": "أنشئ سيرتك الذاتية مجاناً",
    "hero.cta.login": "تسجيل الدخول",
    "hero.card.newInterest": "طلب اهتمام جديد",
    "hero.card.view": "عرض",
    "hero.card.later": "لاحقاً",
    "hero.card.matchScore": "نقاط ATS",
    "hero.card.verified": "متوافق مع ATS",
    "hero.card.exp": "سنوات خبرة",
    "hero.card.projects": "مشاريع",
    "hero.mock.role": "ملف احترافي",
    "hero.mock.name": "أمين عمراني",
    "hero.mock.notification": "تنبيه وظيفة",
    "hero.mock.crew": "فريق التوظيف",
    "hero.mock.welcome": "\"سيرتك الذاتية اجتازت الفرز الأولي! نود تحديد موعد للمقابلة.\"",
    "hero.mock.preference": "الدور",
    "hero.mock.remote": "عن بعد",
    "hero.mock.location": "الموقع",
    "hero.mock.city": "الجزائر، د.ج",
    "hero.mock.status": "التوفر",
    "hero.mock.available": "فوري",

    // Features ("Why Traviit?")
    "features.title.prefix": "لماذا",
    "features.title.highlight": "ترافيت؟",
    "features.description": "نقدم لك الأدوات التي تحتاجها لتبرز في سوق العمل الجزائري.",
    "features.1.title": "لوحة تحكم للمسار المهني",
    "features.1.desc": "تتبع عدد المرات التي تم فيها استعراض سيرتك ومن هم مسؤولو HR المهتمون بملفك.",
    "features.2.title": "بيئة تواصل آمنة",
    "features.2.desc": "خصوصيتك أولويتنا؛ بياناتك مشفرة ولا تظهر إلا لأصحاب العمل الموثقين لدينا.",
    "features.3.title": "تواصل مباشر",
    "features.3.desc": "لا نكتفي بإنشاء السيرة، بل نوصلك مباشرة بمدراء التوظيف في كبرى الشركات.",
    "features.4.title": "مطابقة ذكية",
    "features.4.desc": "خوارزمياتنا تبرز ملفك الشخصي للشركات التي تبحث خصيصاً عن مهاراتك.",

    // Timeline ("How it works?")
    "timeline.badge": "خطوات بسيطة",
    "timeline.title": "كيف تعمل Traviit؟",
    "timeline.desc": "اختر مسارك.",
    "timeline.toggle.seeker": "باحث عن عمل",
    "timeline.toggle.recruiter": "مسؤول توظيف HR",

    // Seeker Steps
    "timeline.seeker.title": "طوّر مسارك المهني للباحث عن عمل",
    "timeline.seeker.step1.title": "املأ بياناتك",
    "timeline.seeker.step1.desc": "أدخل خبراتك ومهاراتك وسيقوم محررنا الذكي بتنسيقها تلقائياً.",
    "timeline.seeker.step2.title": "اختر القالب",
    "timeline.seeker.step2.desc": "اختر من بين مجموعة متنوعة من القوالب الاحترافية التي تناسب تخصصك.",
    "timeline.seeker.step3.title": "حمل وقدم",
    "timeline.seeker.step3.desc": "حمّل نسختك الجاهزة للطباعة والتقديم، وافتح أبواباً جديدة لمستقبلك المهني اليوم.",

    // Recruiter Steps
    "timeline.recruiter.title": "طوّر كفاءة مؤسستك لمسؤول التوظيف",
    "timeline.recruiter.step1.title": "فرز آلي ذكي (Smart Filtering)",
    "timeline.recruiter.step1.desc": "نظامنا يحلل مهارات المرشحين ويطابقها مع متطلبات وظيفتك بنسبة دقة تصل إلى 95%.",
    "timeline.recruiter.step2.title": "إدارة التوظيف",
    "timeline.recruiter.step2.desc": "تواصل مع المرشحين، نظم المقابلات، واتخذ قرار التوظيف عبر لوحة تحكم واحدة متكاملة.",
    "timeline.recruiter.step3.title": "سير ذاتية موحدة المعايير",
    "timeline.recruiter.step3.desc": "وداعاً لتشتت التنسيقات؛ جميع الملفات تصلك بتنسيق احترافي موحد يسهل عليك المقارنة السريعة.",

    // Stats
    "stats.jobs.total": "+700 وظيفة دوام كامل منذ الإطلاق",
    "stats.jobs.students": "فرص طلابية",
    "stats.community": "+14,000 عضو في المجتمعات",
    "stats.active_hr": "أكثر من 50 مسؤول توظيف ينشرون بنشاط",
    "stats.whatsapp.title": "انضم لمجتمعنا",
    "stats.whatsapp.desc": "احصل على تنبيهات الوظائف فوراً عبر واتساب. اختر القناة التي تناسب مرحلتك المهنية.",
    "stats.btn.fulltime": "Traviit للتوظيف",
    "stats.btn.student": "Traviit",

    // Dashboard
    "dashboard.whoViewed": "تطابق الوظائف",
    "dashboard.realTime": "مباشر",
    "dashboard.unlocked": "تطابق عالي",
    "dashboard.pending": "مراجعة",
    "dashboard.denied": "تمت المشاهدة",
    "dashboard.tooltip": "محتوى محسن للـ ATS",
    "dashboard.title": "قاعدة بيانات محدثة لحظياً",
    "dashboard.desc": "لا مزيد من الاتصال بمرشحين حصلوا على وظائف بالفعل؛ ترافيت تمنحك الأولوية للملفات \"المتاحة للعمل الآن\".",
    "dashboard.list1": "+2,500 ملف نشط في الشهر الماضي.",
    "dashboard.list2": "+45 شركة موثقة توظف الآن.",
    "dashboard.list3": "معدل استجابة للمقابلات أعلى بـ 3 أضعاف.",
    "dashboard.cta": "ابدأ في بناء مسارك المهني",
    "dashboard.mock.company1": "بروفاكس",
    "dashboard.mock.desc1": "تكنولوجيا • الجزائر",
    "dashboard.mock.time1": "تطابق 95%",
    "dashboard.mock.company2": "تكنو",
    "dashboard.mock.desc2": "تجارة • الجزائر",
    "dashboard.mock.time2": "تطابق 88%",
    "dashboard.mock.company3": "سي بي أش",
    "dashboard.mock.desc3": "أدوية • قسنطينة",
    "dashboard.mock.time3": "شوهد مؤخراً",

    "testimonials.title": "كن جزءاً من مستقبل التوظيف الذكي",
    "testimonials.desc": "آراء حقيقية من كفاءات وجدت طريقها، ومسؤولي توظيف بنوا فرق أحلامهم.",
    "testimonials.1.text": "\"استخدمت منشئ السيرة الذاتية المجاني وحصلت على 3 مقابلات في أسبوعي الأول. القالب المتوافق مع ATS يعمل حقاً!\"",
    "testimonials.1.role": "مهندس برمجيات",
    "testimonials.2.text": "\"بسيط وسريع واحترافي. لم أضطر للقلق بشأن التنسيق على الإطلاق. أنصح به بشدة.\"",
    "testimonials.2.role": "أخصائي تسويق",
    "testimonials.3.text": "\"الاتصال المباشر بمسؤولي التوظيف غيّر قواعد اللعبة. تخطيت استمارات التقديم اللانهائية.\"",
    "testimonials.3.role": "مدير مشروع",
    "testimonials.4.text": "\"وأخيراً منصة في الجزائر تفهم ما تبحث عنه الشركات العالمية.\"",
    "testimonials.4.role": "محلل بيانات",
    
    "cta.title": "هل أنت مستعد لخطوتك المهنية القادمة؟",
    "cta.desc": "حوّل خبراتك إلى سيرة ذاتية احترافية، واحصل على مطابقة فورية مع وظيفة أحلامك.",
    "cta.join": "أنشئ سيرتك الآن",
    "cta.contact": "اتصل بالدعم",

    "recruiter.landing.title": "هل تبحث عن الكفاءة المثالية؟",
    "recruiter.landing.desc": "تصفح قواعد بياناتنا المحدثة، واستخدم أدوات الفلترة الذكية للوصول للكفاءة المناسبة في ثوانٍ.",
    "recruiter.landing.cta": "انضم كمسؤول توظيف",
    "recruiter.landing.verified": "بيانات موثقة",
    "recruiter.landing.check": "فلترة ذكية",

    "faq.title": "الأسئلة الشائعة (FAQ)",
    "faq.q1": "هل يمكنني تحميل سيرتي الذاتية واستخدامها خارج المنصة؟",
    "faq.a1": "نعم، ترافيت تتيح لك تحميل سيرتك الذاتية بتنسيقات احترافية جاهزة للطباعة أو الإرسال عبر الإيميل في أي وقت.",
    "faq.q2": "هل يمكنني تحديث بياناتي لاحقاً؟",
    "faq.a2": "بكل تأكيد، ملفك محفوظ ويمكنك تعديله في أي وقت ومن أي جهاز.",
    "faq.q3": "كيف تضمن ترافيت وصول ملفي لمسؤولي التوظيف؟",
    "faq.a3": "بمجرد اكتمال ملفك بنسبة 100%، يظهر اسمك تلقائياً في نتائج البحث الذكي لدى الشركات التي تبحث عن مهاراتك.",
    "faq.q4": "هل منصة ترافيت تضمن لي الحصول على وظيفة؟",
    "faq.a4": "نحن نضمن لك سيرة ذاتية احترافية وظهوراً ذكياً أمام الشركات الكبرى، مما يرفع فرصك في التوظيف بشكل كبير مقارنة بالطرق التقليدية.",
    "faq.q5": "هل بياناتي الشخصية (رقم الهاتف والإيميل) محمية؟",
    "faq.a5": "بكل تأكيد، ترافيت تلتزم بأعلى معايير حماية البيانات. معلومات التواصل الخاصة بك لا تظهر إلا للشركات التي تتقدم إليها رسمياً أو التي تمنحها أنت الإذن بذلك.",

    "contact.title": "تواصل معنا",
    "contact.desc": "لديك أسئلة؟ نحن هنا للمساعدة.",
    "contact.emailUs": "راسلنا",
    "contact.visitUs": "زرنا",
    "contact.form.name": "الاسم",
    "contact.form.email": "البريد الإلكتروني",
    "contact.form.subject": "الموضوع",
    "contact.form.message": "الرسالة",
    "contact.btn.send": "إرسال الرسالة",

    "footer.privacy": "سياسة الخصوصية",
    "footer.transparency": "شروط الاستخدام",
    "footer.linkedin": "لينكد إن",
    "footer.facebook": "فيسبوك",
    "footer.instagram": "انستغرام",
    "footer.copyright": "© 2024 Traviit. جميع الحقوق محفوظة.",
    ": "بدل صنعت من أجل الجزائر",

    "login.title": "مرحباً بعودتك",
    "login.subtitle": "أدخل بيانات الاعتماد للوصول إلى لوحة التحكم.",
    "login.noAccount": "ليس لديك حساب؟",
    "login.register": "سجل الآن",
    "login.submit": "دخول",
    
    "recruiter.login.title": "دخول الشركات",
    "recruiter.login.subtitle": "الوصول إلى قاعدة المواهب.",
    "recruiter.login.cta": "تسجيل الدخول",
    "recruiter.login.new": "جديد في Traviit؟",
    "recruiter.login.register": "سجل شركتك",

    "recruiter.form.corporate": "بوابة الشركات",
    "recruiter.form.title": "تسجيل الشركات",
    "recruiter.form.subtitle": "أنشئ حساباً للوصول إلى المواهب الجزائرية الموثقة.",
    "recruiter.form.section.company": "بيانات الشركة",
    "recruiter.form.section.rep": "بيانات الممثل",
    "recruiter.form.section.security": "الأمان",
    "recruiter.form.companyName": "اسم الشركة",
    "recruiter.form.industry": "القطاع",
    "recruiter.form.website": "الموقع الإلكتروني (اختياري)",
    "recruiter.form.fullName": "الاسم الكامل",
    "recruiter.form.position": "المسمى الوظيفي",
    "recruiter.form.workEmail": "البريد المهني",
    "recruiter.form.phone": "رقم الهاتف",
    "recruiter.form.password": "كلمة المرور",
    "recruiter.form.confirmPassword": "تأكيد كلمة المرور",
    "recruiter.form.submit": "تسجيل المؤسسة",
    "recruiter.form.portal": "بوابة الشركات",

    "dash.menu.profile": "نظرة عامة",
    "dash.menu.cvs": "السير الذاتية",
    "dash.section.identity": "الهوية",
    "dash.section.exp": "الخبرة",
    "dash.section.edu": "التعليم",
    "dash.section.skills": "المهارات",
    "dash.section.admin": "إداري",
    "dash.cv.choose": "اختر القالب",
    "dash.cv.modern": "عصري",
    "dash.cv.classic": "كلاسيكي",
    "dash.cv.creative": "إبداعي",
    "dash.cv.download": "تحميل كصورة",

    "dash.search.placeholder": "ابحث بالمسمى الوظيفي أو المهارة...",
    "dash.filter.reset": "إعادة تعيين المرشحات",
    "dash.filter.showAdvanced": "إظهار المرشحات المتقدمة",
    "dash.filter.hideAdvanced": "إخفاء المرشحات المتقدمة",
    "dash.discovery.title": "اكتشاف المواهب",
    "dash.discovery.subtitle": "تم العثور على {count} مرشح موثق يطابق معاييرك.",
    "dash.menu.search": "بحث المواهب",
    "dash.menu.saved": "المحفوظة",
    "dash.menu.jobs": "وظائفي",
    "dash.menu.settings": "الإعدادات",
    
    "cand.matchScore": "نسبة التطابق",
    "cand.salary": "توقعات الراتب",
    "cand.availability": "التوفر",
    "cand.about": "نبذة عن المرشح",
    "cand.skills": "المهارات التقنية",
    "cand.history": "التاريخ المهني",
    "cand.education": "التعليم",
    "cand.profile": "ملف المرشح",
    "cand.verifiedEdu": "مؤهل موثق",
    "cand.yearsExp": "سنوات خبرة",
    
    "btn.backToSearch": "العودة للبحث",
    "btn.viewProfile": "عرض الملف",
    "btn.viewCV": "عرض السيرة",
    "btn.whatsapp": "واتساب",
    "btn.save": "حفظ",
    "btn.saved": "محفوظ",
    
    "filter.experience": "الخبرة",
    "filter.salary": "الراتب",
    "filter.education": "التعليم",
    "filter.availability": "التوفر",
    "filter.workType": "نظام العمل",
    "filter.industry": "القطاع",
    "filter.datePosted": "تاريخ النشر",
    "filter.language": "اللغة",

    "wizard.step.identity": "المعلومات الشخصية",
    "wizard.step.target": "الهدف الوظيفي",
    "wizard.step.experience": "الخبرة",
    "wizard.step.education": "التعليم",
    "wizard.step.admin": "لوجستيات",
    "wizard.step.review": "مراجعة",
    "wizard.step.desc.1": "ابدأ بالتحقق من بياناتك الشخصية.",
    "wizard.step.desc.2": "حدد أهدافك المهنية وتفضيلاتك.",
    "wizard.step.desc.3": "اعرض تاريخك المهني وإنجازاتك.",
    "wizard.step.desc.4": "أدرج خلفيتك الأكاديمية والشهادات.",
    "wizard.step.desc.5": "تفاصيل إدارية ولوجستية.",
    "wizard.step.desc.6": "راجع معلوماتك قبل الإرسال.",

    "form.firstName": "الاسم",
    "form.lastName": "اللقب",
    "form.aboutMe": "نبذة عني",
    "form.aboutMe.placeholder": "صف نفسك بإيجاز...",
    "form.dob": "تاريخ الميلاد",
    "form.pob": "مكان الميلاد",
    "form.gender": "الجنس",
    "form.nationality": "الجنسية",
    "form.gender.male": "ذكر",
    "form.gender.female": "أنثى",

    "form.phone": "رقم الهاتف",
    "form.email": "البريد الإلكتروني",
    "form.website": "الموقع الإلكتروني",
    "form.linkedIn": "LinkedIn",
    "form.otherLink": "رابط آخر (معرض أعمال/مدونة)",
    "form.github": "GitHub",
    "form.whatsapp": "رقم الواتساب",
    "form.whatsapp.placeholder": "+213...",
    "form.whatsapp.hint": "يجب أن يبدأ بـ +213 ويتبعه 5 أو 6 أو 7...",
    "form.viber": "Viber",
    "form.telegram": "Telegram",
    "form.toggle.messaging": "تطبيقات المراسلة",
    "form.toggle.socials": "روابط التواصل",

    "form.address.type": "نوع العنوان",
    "form.address.street": "العنوان",
    "form.address.zip": "الرمز البريدي",
    "form.address.city": "الولاية",
    "form.address.city.placeholder": "اختر الولاية",
    "form.address.country": "الدولة",
    "form.address.home": "منزل",
    "form.address.work": "عمل",
    "form.address.other": "آخر",

    "form.targetJobTitle": "المسمى الوظيفي المرغوب",
    "form.targetJobTitle.placeholder": "مثال: محاسب، مهندس برمجيات",
    "form.targetLocation": "المكان المرغوب (الولاية)",
    "form.targetLocation.placeholder": "اختر الولاية المفضلة",
    "form.targetCompany": "اسم الشركة (اختياري)",
    "form.careerStage": "المرحلة المهنية",
    "form.employmentType": "نمط التوظيف",
    "form.careerGoal": "الهدف",
    "form.careerGoal.placeholder": "صف أهدافك المهنية...",
    "form.toggle.company": "شركة مستهدفة",
    "form.toggle.goal": "الهدف الوظيفي",
    "form.noticePeriod": "فترة الإخطار",
    "form.noticePeriod.placeholder": "اختر التوفر",
    "form.notice.immediate": "فوري",
    "form.notice.1month": "شهر واحد",
    "form.notice.3months": "3 أشهر",

    "form.stage.student": "طالب",
    "form.stage.intern": "متدرب",
    "form.stage.fresh_graduate": "خريج جديد",
    "form.stage.junior": "مبتدئ (1-3 سنوات)",
    "form.stage.mid_level": "متوسط (3-5 سنوات)",
    "form.stage.senior": "خبير (5+ سنوات)",
    "form.stage.executive": "مدير / تنفيذي",

    "form.emp.full_time": "دوام كامل",
    "form.emp.part_time": "دوام جزئي",
    "form.emp.freelance": "عمل حر (Freelance)",
    "form.emp.internship": "تدريب (Stage)",
    "form.emp.temporary": "مؤقت",
    "form.emp.contract": "عقد محدد",

    "form.nationalService": "الخدمة الوطنية",
    "form.drivingLicense": "رخص السياقة",
    "form.drivingPermits.placeholder": "اختر الرخص (مثلاً B، C...)",
    "form.additionalInfo": "معلومات إضافية",
    "form.photoUrl": "رابط الصورة الشخصية",

    "form.ns.exempted": "معفى",
    "form.ns.postponed": "مؤجل",
    "form.ns.completed": "منجز",
    "form.ns.not_concerned": "غير معني",

    "form.exp.title": "الخبرة المهنية",
    "form.exp.add": "إضافة خبرة",
    "form.jobTitle": "المسمى الوظيفي",
    "form.company": "اسم الشركة",
    "form.location": "الموقع",
    "form.locationType": "نوع الموقع",
    "form.loc.remote": "عن بعد",
    "form.loc.hybrid": "هجين",
    "form.loc.onsite": "في الموقع",
    "form.description": "ملخص الدور (اختياري)",
    "form.description.placeholder": "وصف مختصر للدور...",
    "form.skillsUsed": "التقنيات/المهارات المستخدمة (اختياري)",
    "form.skillsUsed.placeholder": "مثال: React, Excel, إدارة (مفصولة بفاصلة)",
    "form.activity": "نشاط الشركة",
    "form.startDate": "تاريخ البدء",
    "form.endDate": "تاريخ الانتهاء",
    "form.current": "أعمل هنا حالياً",
    "form.achievements": "الإنجازات الرئيسية (إنجاز لكل سطر)",
    "form.achievements.placeholder": "- زيادة المبيعات بنسبة 20%\n- إدارة فريق من 5 أشخاص",
    "form.exp.none": "لم تتم إضافة خبرات بعد.",

    "form.edu.title": "التعليم",
    "form.edu.add": "إضافة مؤهل",
    "form.degree": "المؤهل / الشهادة",
    "form.institution": "المؤسسة / الجامعة",
    "form.gradYear": "سنة التخرج",
    "form.edu.none": "لم تتم إضافة مؤهلات بعد.",

    "form.skills.hard": "المهارات التقنية (Hard Skills)",
    "form.skills.soft": "المهارات الشخصية (Soft Skills)",
    "form.skills.placeholder": "اختر أو اكتب للإضافة...",
    "form.skills.none": "لم يتم اختيار مهارات.",

    "form.lang.title": "اللغات",
    "form.lang.add": "إضافة لغة",
    "form.lang.name": "اللغة",
    "form.lang.name.placeholder": "مثال: الإنجليزية، العربية",
    "form.lang.level": "المستوى",
    "form.lang.native": "لغة أم",
    "form.lang.beginner": "مبتدئ",
    "form.lang.intermediate": "متوسط",
    "form.lang.good": "جيد",
    "form.lang.advanced": "متقدم",

    "form.admin.title": "معلومات إدارية ولوجستية",
    "form.accommodation": "هل تحتاج إيواء؟",
    "form.smoking": "مدخن؟",
    "form.ref.name": "اسم المشرف السابق",
    "form.ref.phone": "هاتف المشرف",
    "form.ref.rel": "العلاقة",

    "btn.next": "التالي",
    "btn.back": "السابق",
    "btn.preview": "معاينة السيرة الذاتية",
    "btn.submit": "إرسال الملف",
    "btn.cancel": "إلغاء",
    "btn.share": "مشاركة",
    "share.text": "تصفح ملفي المهني الموثق على Traviit.",
    "btn.copy": "نسخ الرابط",
    "btn.copied": "تم النسخ!",
    "msg.required": "مطلوب",
    "msg.minSkills": "يرجى إضافة 3 مهارات تقنية على الأقل.",
    "msg.minLangs": "يرجى إضافة لغتين على الأقل.",
    "msg.invalidWhatsApp": "غير صحيح. يجب أن يبدأ بـ +213 ويتبعه 5 أو 6 أو 7.",
    "msg.invalidEmail": "يرجى إدخال بريد إلكتروني صحيح.",
    "msg.passwordMismatch": "كلمات المرور غير متطابقة.",
    "msg.passwordWeak": "يجب أن تكون كلمة المرور 6 أحرف على الأقل.",
    "msg.saveEntry": "يرجى حفظ أو إلغاء الإدخال الحالي",
    "msg.done": "تم بنجاح!",
    "msg.done.desc": "يتم تشفير ملفك الشخصي. ستتلقى بريداً إلكترونياً للتحقق قريباً.",
    "dash.welcome": "مرحباً بك",
    "dash.viewCV": "عرض السيرة الذاتية",
    "dash.editProfile": "تعديل الملف",
    "dash.status": "حالة الملف",
    "dash.status.active": "نشط",
    "dash.stats.views": "مشاهدات الملف",
    "dash.stats.appears": "ظهور في البحث",
    "dash.stats.requests": "طلبات التواصل",
    "modal.signup.title": "تأمين حسابك",
    "modal.signup.desc": "قم بتعيين كلمة مرور للوصول إلى لوحة التحكم الخاصة بك. تم التحقق من تفاصيل الاتصال الخاصة بك.",
    "form.password": "أنشئ كلمة مرور",
    "form.confirmPassword": "تأكيد كلمة مرور",
    "btn.completeSignup": "إتمام التسجيل",

    "common.none": "لا يوجد",
    "common.present": "حاضر",
    "common.comingSoon": "قريباً",
    "common.years": "سنوات",
    "common.month": "شهر",
    "common.months": "أشهر",
    "common.immediate": "فوري",

    "doc.settings": "إعدادات وثيقة السيرة الذاتية",
    "doc.lang": "لغة الوثيقة المولدة",
    "review.identity": "الهوية",
    "review.target": "الهدف الوظيفي",
    "review.skills": "المهارات واللغات",
    "review.admin": "إداري وإضافي",
    "review.generated": "تم إنشاؤه بواسطة Traviit",
    "review.mode": "وضع المراجعة",
    "review.desc": "تحقق من التفاصيل قبل الانتهاء.",
    "terms.label": "أؤكد أن المعلومات المقدمة دقيقة وأوافق على",
    "terms.use": "شروط الاستخدام",
    "terms.privacy": "سياسة الخصوصية",

    "job.post.new": "نشر وظيفة",
    "job.post.title": "المسمى الوظيفي",
    "job.post.location": "الموقع",
    "job.post.type": "نظام العمل",
    "job.post.salary": "نطاق الراتب",
    "job.post.desc": "الوصف الوظيفي",
    "job.post.req": "المتطلبات",
    "job.post.submit": "نشر الوظيفة",
    "job.post.success": "تم نشر الوظيفة بنجاح!",
    "job.list.active": "الوظائف النشطة",
    "job.list.noJobs": "لا توجد وظائف نشطة. انشر وظيفتك الأولى!",
    "job.list.applicants": "المتقدمون",

    // Month translations
    "month.01": "يناير",
    "month.02": "فبراير",
    "month.03": "مارس",
    "month.04": "أبريل",
    "month.05": "مايو",
    "month.06": "يونيو",
    "month.07": "يوليو",
    "month.08": "أغسطس",
    "month.09": "سبتمبر",
    "month.10": "أكتوبر",
    "month.11": "نوفمبر",
    "month.12": "ديسمبر",
    "year.present": "الحاضر"
};
