
export const en = {
    "nav.talent": "Create CV",
    "nav.companies": "Companies",
    "nav.features": "Features",
    "nav.faq": "FAQ",
    "nav.login": "Login",
    "nav.getStarted": "Get Started",
    "nav.hiring": "Hiring?",
    "nav.joinTalent": "Create CV",
    "nav.appearance": "Appearance",
    "nav.language": "Language",
    "nav.mode.dark": "Dark",
    "nav.mode.light": "Light",
    "nav.back": "Back",
    "nav.logout": "Log out",
    
    // Hero
    "hero.badge": "Professional CV Builder",
    "hero.title.prefix": "Your Career...",
    "hero.title.highlight": "Starts with Transparency.",
    "hero.description": "Build a professional CV in minutes. Connect with top companies in a secure, verified environment.",
    "hero.cta.find": "Explore Jobs",
    "hero.cta.join": "Create Free CV",
    "hero.cta.login": "Sign In",
    "hero.card.verified": "ATS FRIENDLY",
    "hero.card.matchScore": "ATS Score",
    "hero.card.exp": "Exp",
    "hero.card.projects": "Projects",
    "hero.mock.role": "Professional Profile",
    "hero.mock.name": "Amine Amrani",
    "hero.mock.notification": "Job Alert",
    "hero.mock.crew": "Recruitment Team",
    "hero.mock.welcome": "\"Your CV passed the initial screening! We would like to schedule an interview.\"",
    "hero.mock.preference": "Role",
    "hero.mock.remote": "Remote",
    "hero.mock.location": "Location",
    "hero.mock.city": "Algiers, DZ",
    "hero.mock.status": "Availability",
    "hero.mock.available": "Immediate",

    // Features ("Why Traviit?")
    "features.title.prefix": "Why",
    "features.title.highlight": "Traviit?",
    "features.description": "Advanced tools for a smarter career path.",
    "features.1.title": "Career Dashboard",
    "features.1.desc": "Track how many times your CV is viewed and which HR managers are interested in your profile.",
    "features.2.title": "Secure Environment",
    "features.2.desc": "Your privacy is our priority; your data is encrypted and only visible to verified employers.",
    "features.3.title": "Direct Connection",
    "features.3.desc": "Connect directly with hiring managers at major companies without intermediaries.",
    "features.4.title": "Smart Matching",
    "features.4.desc": "Our algorithms highlight your profile to companies specifically looking for your skillset.",

    // Timeline ("How it works?")
    "timeline.badge": "How it works",
    "timeline.title": "How Traviit Works?",
    "timeline.desc": "Choose your path.",
    "timeline.toggle.seeker": "Job Seeker",
    "timeline.toggle.recruiter": "Recruiter (HR)",
    
    // Seeker Steps
    "timeline.seeker.title": "Develop Your Career Path",
    "timeline.seeker.step1.title": "Fill Your Data",
    "timeline.seeker.step1.desc": "Enter your experience and skills, and our smart editor will format them automatically.",
    "timeline.seeker.step2.title": "Choose Template",
    "timeline.seeker.step2.desc": "Choose from a variety of professional templates that suit your specialization.",
    "timeline.seeker.step3.title": "Download & Apply",
    "timeline.seeker.step3.desc": "Download your print-ready version and open new doors for your professional future today.",

    // Recruiter Steps
    "timeline.recruiter.title": "Boost Your Organization's Efficiency",
    "timeline.recruiter.step1.title": "Smart Filtering",
    "timeline.recruiter.step1.desc": "Our system analyzes candidate skills and matches them to your job requirements with up to 95% accuracy.",
    "timeline.recruiter.step2.title": "Recruitment Management",
    "timeline.recruiter.step2.desc": "Communicate with candidates, organize interviews, and make hiring decisions via one integrated dashboard.",
    "timeline.recruiter.step3.title": "Standardized CVs",
    "timeline.recruiter.step3.desc": "No more scattered formats; all files arrive in a unified professional format for quick comparison.",

    // Stats
    "stats.jobs.total": "Full Time Jobs Since Launch",
    "stats.jobs.students": "Student Opportunities",
    "stats.community": "Members Across Communities",
    "stats.active_hr": "HR Actively Posting",
    "stats.whatsapp.title": "Join the Elite Community",
    "stats.whatsapp.desc": "Get instant job alerts directly on WhatsApp. Choose the channel that fits your career stage.",
    "stats.btn.fulltime": "Traviit Recruitment",
    "stats.btn.student": "Traviit",

    // Dashboard
    "dashboard.whoViewed": "Job Matches",
    "dashboard.realTime": "LIVE",
    "dashboard.unlocked": "High Match",
    "dashboard.pending": "Reviewing",
    "dashboard.denied": "Seen",
    "dashboard.tooltip": "ATS Optimized Content",
    "dashboard.title": "Real-time Database",
    "dashboard.desc": "No more calling candidates who are already hired. Traviit prioritizes profiles that are 'Available for Work Now'.",
    "dashboard.list1": "+2,500 Active Profiles in the last month.",
    "dashboard.list2": "+45 Verified Companies hiring now.",
    "dashboard.list3": "3x Higher Interview Response Rate.",
    "dashboard.cta": "Start Building Your Career",
    "dashboard.mock.company1": "Prophex",
    "dashboard.mock.desc1": "Tech • Algiers",
    "dashboard.mock.time1": "95% Match",
    "dashboard.mock.company2": "Techno",
    "dashboard.mock.desc2": "Retail • Algiers",
    "dashboard.mock.time2": "88% Match",
    "dashboard.mock.company3": "CPH",
    "dashboard.mock.desc3": "Pharma • Constantine",
    "dashboard.mock.time3": "Recently Viewed",

    "testimonials.title": "Join the Future of Smart Hiring",
    "testimonials.desc": "Real opinions from talents who found their way, and recruiters who built their dream teams.",
    "testimonials.1.text": "\"I used the free CV builder and got 3 interviews in my first week. The ATS-friendly template really works!\"",
    "testimonials.1.role": "Software Engineer",
    "testimonials.2.text": "\"Simple, fast, and professional. I didn't have to worry about formatting at all. Highly recommended.\"",
    "testimonials.2.role": "Marketing Specialist",
    "testimonials.3.text": "\"The direct connection to recruiters is a game changer. I skipped the endless application forms.\"",
    "testimonials.3.role": "Project Manager",
    "testimonials.4.text": "\"Finally a platform in Algeria that understands what international companies are looking for.\"",
    "testimonials.4.role": "Data Analyst",
    
    "cta.title": "Ready for your next career step?",
    "cta.desc": "Turn your experience into a professional CV and get instant matching with your dream job.",
    "cta.join": "Create CV Now",
    "cta.contact": "Contact Support",

    "recruiter.landing.title": "Looking for the Perfect Talent?",
    "recruiter.landing.desc": "Browse our updated databases and use smart filtering tools to reach the right competence in seconds.",
    "recruiter.landing.cta": "Join as Recruiter",
    "recruiter.landing.verified": "Verified Data",
    "recruiter.landing.check": "Smart Filtering",

    "faq.title": "Frequently Asked Questions (FAQ)",
    "faq.q1": "Can I download my CV and use it outside the platform?",
    "faq.a1": "Yes, Traviit allows you to download your CV in professional formats ready for printing or emailing at any time.",
    "faq.q2": "Can I update my data later?",
    "faq.a2": "Certainly, your file is saved and you can edit it at any time and from any device.",
    "faq.q3": "How does Traviit ensure my profile reaches recruiters?",
    "faq.a3": "Once your profile is 100% complete, your name automatically appears in smart search results for companies looking for your skills.",
    "faq.q4": "Does Traviit guarantee me a job?",
    "faq.a4": "We guarantee you a professional CV and smart visibility before major companies, which significantly increases your hiring chances compared to traditional methods.",
    "faq.q5": "Is my personal data (phone and email) protected?",
    "faq.a5": "Absolutely. Traviit adheres to the highest data protection standards. Your contact info is only shown to companies you apply to or authorize.",

    "contact.title": "Get in touch",
    "contact.desc": "Have questions? We're here to help.",
    "contact.emailUs": "Email Us",
    "contact.visitUs": "Visit Us",
    "contact.form.name": "Your Name",
    "contact.form.email": "Your Email",
    "contact.form.subject": "Subject",
    "contact.form.message": "Message",
    "contact.btn.send": "Send Message",

    "footer.privacy": "Privacy Policy",
    "footer.transparency": "Terms of Use",
    "footer.linkedin": "LinkedIn",
    "footer.facebook": "Facebook",
    "footer.instagram": "Instagram",
    "footer.copyright": "© 2024 Traviit. All rights reserved.",
    "footer.madeFor": "Made for Algeria",

    "login.title": "Welcome Back",
    "login.subtitle": "Enter your credentials to access your dashboard.",
    "login.noAccount": "Don't have an account?",
    "login.register": "Sign up",
    "login.submit": "Log In",
    
    "recruiter.login.title": "Recruiter Login",
    "recruiter.login.subtitle": "Access your talent pipeline.",
    "recruiter.login.cta": "Sign In",
    "recruiter.login.new": "New to Traviit?",
    "recruiter.login.register": "Register Company",
    
    "recruiter.form.corporate": "Corporate Access",
    "recruiter.form.title": "Recruiter Registration",
    "recruiter.form.subtitle": "Create an account to access verified Algerian talent.",
    "recruiter.form.section.company": "Company Details",
    "recruiter.form.section.rep": "Representative Details",
    "recruiter.form.section.security": "Security",
    "recruiter.form.companyName": "Company Name",
    "recruiter.form.industry": "Industry",
    "recruiter.form.website": "Website (Optional)",
    "recruiter.form.fullName": "Full Name",
    "recruiter.form.position": "Position Title",
    "recruiter.form.workEmail": "Work Email",
    "recruiter.form.phone": "Phone Number",
    "recruiter.form.password": "Password",
    "recruiter.form.confirmPassword": "Confirm Password",
    "recruiter.form.submit": "Register Organization",
    "recruiter.form.portal": "Corporate Portal",
    
    "dash.menu.profile": "Profile Overview",
    "dash.menu.cvs": "My CVs",
    "dash.section.identity": "Identity",
    "dash.section.exp": "Experience",
    "dash.section.edu": "Education",
    "dash.section.skills": "Skills",
    "dash.section.admin": "Admin",
    "dash.cv.choose": "Choose Template",
    "dash.cv.modern": "Modern",
    "dash.cv.classic": "Classic",
    "dash.cv.creative": "Creative",
    "dash.cv.download": "Download Image",

    "dash.search.placeholder": "Search by job title or skill...",
    "dash.filter.reset": "Reset All Filters",
    "dash.filter.showAdvanced": "Show Advanced Filters",
    "dash.filter.hideAdvanced": "Hide Advanced Filters",
    "dash.discovery.title": "Talent Discovery",
    "dash.discovery.subtitle": "Found {count} verified candidates matching your criteria.",
    "dash.menu.search": "Talent Search",
    "dash.menu.saved": "Saved",
    "dash.menu.jobs": "My Jobs",
    "dash.menu.settings": "Settings",
    
    "cand.matchScore": "Match Score",
    "cand.salary": "Salary Expectation",
    "cand.availability": "Availability",
    "cand.about": "About Candidate",
    "cand.skills": "Technical Skills",
    "cand.history": "Professional History",
    "cand.education": "Education",
    "cand.profile": "Candidate Profile",
    "cand.verifiedEdu": "Verified Qualification",
    "cand.yearsExp": "Years Exp.",
    
    "btn.backToSearch": "Back to Search",
    "btn.viewProfile": "View Profile",
    "btn.viewCV": "View CV",
    "btn.whatsapp": "WhatsApp",
    "btn.save": "Save",
    "btn.saved": "Saved",
    
    "filter.experience": "Experience",
    "filter.education": "Education",
    "filter.availability": "Availability",
    "filter.workType": "Work Type",
    "filter.industry": "Industry",
    "filter.datePosted": "Date Posted",
    "filter.language": "Language",

    "wizard.step.identity": "Personal Info",
    "wizard.step.target": "Career Objective",
    "wizard.step.experience": "Experience",
    "wizard.step.education": "Education",
    "wizard.step.admin": "Logistics",
    "wizard.step.review": "Review",
    "wizard.step.desc.1": "Start by verifying your personal details.",
    "wizard.step.desc.2": "Define your professional goals and preferences.",
    "wizard.step.desc.3": "Showcase your work history and achievements.",
    "wizard.step.desc.4": "List your academic background and degrees.",
    "wizard.step.desc.5": "Administrative details and logistics.",
    "wizard.step.desc.6": "Review your information before submission.",

    "form.firstName": "First Name",
    "form.lastName": "Last Name",
    "form.aboutMe": "About Me",
    "form.aboutMe.placeholder": "Briefly describe yourself...",
    "form.dob": "Date of Birth",
    "form.pob": "Place of Birth",
    "form.gender": "Gender",
    "form.nationality": "Nationality",
    "form.gender.male": "Male",
    "form.gender.female": "Female",

    "form.phone": "Phone Number",
    "form.email": "Email Address",
    "form.website": "Website",
    "form.linkedIn": "LinkedIn",
    "form.otherLink": "Other Link (Portfolio/Blog)",
    "form.github": "GitHub",
    "form.whatsapp": "WhatsApp Number",
    "form.whatsapp.placeholder": "+213...",
    "form.whatsapp.hint": "Must be +213 followed by 5, 6, or 7...",
    "form.viber": "Viber",
    "form.telegram": "Telegram",
    "form.toggle.messaging": "Messaging Apps",
    "form.toggle.socials": "Social Links",

    "form.address.type": "Address Type",
    "form.address.street": "Address",
    "form.address.zip": "Postal Code",
    "form.address.city": "Wilaya (City)",
    "form.address.city.placeholder": "Select Wilaya",
    "form.address.country": "Country",
    "form.address.home": "Home",
    "form.address.work": "Work",
    "form.address.other": "Other",

    "form.targetJobTitle": "Desired Job Title",
    "form.targetJobTitle.placeholder": "e.g. Accountant, Software Engineer",
    "form.targetLocation": "Desired Location (Wilaya)",
    "form.targetLocation.placeholder": "Select Preferred Wilaya",
    "form.targetCompany": "Target Company (Optional)",
    "form.careerStage": "Career Stage",
    "form.employmentType": "Employment Type",
    "form.careerGoal": "Professional Goal",
    "form.careerGoal.placeholder": "Describe your career objectives...",
    "form.toggle.company": "Target Company",
    "form.toggle.goal": "Career Goal",
    "form.noticePeriod": "Notice Period",
    "form.noticePeriod.placeholder": "Select availability",
    "form.notice.immediate": "Immediate",
    "form.notice.1month": "1 Month",
    "form.notice.3months": "3 Months",
    
    "form.stage.student": "Student",
    "form.stage.intern": "Intern",
    "form.stage.fresh_graduate": "Fresh Graduate",
    "form.stage.junior": "Junior (1-3 years)",
    "form.stage.mid_level": "Mid-Level (3-5 years)",
    "form.stage.senior": "Senior (5+ years)",
    "form.stage.executive": "Executive",

    "form.emp.full_time": "Full Time",
    "form.emp.part_time": "Part Time",
    "form.emp.freelance": "Freelance",
    "form.emp.internship": "Internship",
    "form.emp.temporary": "Temporary",
    "form.emp.contract": "Contract",

    "form.nationalService": "National Service",
    "form.drivingLicense": "Driving Permits",
    "form.drivingPermits.placeholder": "Select permits (e.g. B, C...)",
    "form.additionalInfo": "Additional Information",
    "form.photoUrl": "Photo URL",

    "form.ns.exempted": "Exempted",
    "form.ns.postponed": "Postponed",
    "form.ns.completed": "Completed",
    "form.ns.not_concerned": "Not Concerned",

    "form.exp.title": "Professional Experience",
    "form.exp.add": "Add Experience",
    "form.jobTitle": "Job Title",
    "form.company": "Company Name",
    "form.location": "Location",
    "form.locationType": "Location Type",
    "form.loc.remote": "Remote",
    "form.loc.hybrid": "Hybrid",
    "form.loc.onsite": "On-site",
    "form.description": "Role Summary (Optional)",
    "form.description.placeholder": "Brief description of the role...",
    "form.skillsUsed": "Technologies/Skills Used (Optional)",
    "form.skillsUsed.placeholder": "e.g. React, Excel, Management (comma separated)",
    "form.activity": "Company Activity",
    "form.startDate": "Start Date",
    "form.endDate": "End Date",
    "form.current": "I currently work here",
    "form.achievements": "Key Achievements (One per line)",
    "form.achievements.placeholder": "- Increased sales by 20%\n- Managed team of 5",
    "form.exp.none": "No experience added yet.",

    "form.edu.title": "Education",
    "form.edu.add": "Add Education",
    "form.degree": "Qualification/Degree",
    "form.institution": "Institution/University",
    "form.gradYear": "Graduation Year",
    "form.edu.none": "No education added yet.",

    "form.skills.hard": "Technical Skills (Hard Skills)",
    "form.skills.soft": "Soft Skills",
    "form.skills.placeholder": "Type and press Enter...",
    "form.skills.none": "No skills selected.",

    "form.lang.title": "Languages",
    "form.lang.add": "Add Language",
    "form.lang.name": "Language",
    "form.lang.name.placeholder": "e.g. English, Arabic",
    "form.lang.level": "Proficiency",
    "form.lang.native": "Native",
    "form.lang.beginner": "Beginner",
    "form.lang.intermediate": "Intermediate",
    "form.lang.good": "Good",
    "form.lang.advanced": "Advanced",

    "form.admin.title": "Administrative & Logistics",
    "form.accommodation": "Accommodation Required?",
    "form.smoking": "Smoker?",
    "form.ref.name": "Supervisor Name",
    "form.ref.phone": "Supervisor Phone",
    "form.ref.rel": "Relationship",

    "btn.next": "Next",
    "btn.back": "Back",
    "btn.preview": "Preview CV",
    "btn.submit": "Submit Profile",
    "btn.cancel": "Cancel",
    "btn.share": "Share CV",
    "share.text": "View my verified professional profile on Traviit.",
    "btn.copy": "Copy Link",
    "btn.copied": "Copied!",
    "msg.required": "Required",
    "msg.minSkills": "Please add at least 3 technical skills.",
    "msg.minLangs": "Please add at least 2 languages.",
    "msg.invalidWhatsApp": "Invalid. Must start with +213 followed by 5, 6, or 7 and 8 digits.",
    "msg.invalidEmail": "Please enter a valid email address.",
    "msg.passwordMismatch": "Passwords do not match.",
    "msg.passwordWeak": "Password must be at least 6 characters.",
    "msg.saveEntry": "Please save or cancel the current entry",
    "msg.done": "All Set!",
    "msg.done.desc": "Your profile is being encrypted. You will receive a verification email shortly.",
    "dash.welcome": "Welcome back",
    "dash.viewCV": "View CV",
    "dash.editProfile": "Edit Profile",
    "dash.status": "Profile Status",
    "dash.status.active": "Active",
    "dash.stats.views": "Profile Views",
    "dash.stats.appears": "Search Appearances",
    "dash.stats.requests": "Contact Requests",
    "modal.signup.title": "Secure Your Account",
    "modal.signup.desc": "Set a password to access your dashboard later. Your contact details are already verified.",
    "form.password": "Create Password",
    "form.confirmPassword": "Confirm Password",
    "btn.completeSignup": "Complete Registration",

    "common.none": "None",
    "common.present": "Present",
    "common.comingSoon": "Coming Soon",
    "common.years": "Years",
    "common.month": "Month",
    "common.months": "Months",
    "common.immediate": "Immediate",

    "doc.settings": "CV Document Settings",
    "doc.lang": "Generated Document Language",
    "review.identity": "Identity",
    "review.target": "Target Job",
    "review.skills": "Skills & Languages",
    "review.admin": "Admin & Additional",
    "review.generated": "Generated by Traviit",
    "review.mode": "Review Mode",
    "review.desc": "Check your details before finalizing.",
    "terms.label": "I confirm the information provided is accurate and agree to the",
    "terms.use": "Terms of Use",
    "terms.privacy": "Privacy Policy",

    "job.post.new": "Post a Job",
    "job.post.title": "Job Title",
    "job.post.location": "Location",
    "job.post.type": "Job Type",
    "job.post.salary": "Salary Range",
    "job.post.desc": "Job Description",
    "job.post.req": "Requirements",
    "job.post.submit": "Publish Job",
    "job.post.success": "Job Posted Successfully!",
    "job.list.active": "Active Jobs",
    "job.list.noJobs": "No active jobs found. Post your first one!",
    "job.list.applicants": "Applicants",

    // Month translations
    "month.01": "January",
    "month.02": "February",
    "month.03": "March",
    "month.04": "April",
    "month.05": "May",
    "month.06": "June",
    "month.07": "July",
    "month.08": "August",
    "month.09": "September",
    "month.10": "October",
    "month.11": "November",
    "month.12": "December",
    "year.present": "Present"
};
