
import { en } from './en';

export const fr = {
    ...en, // Fallback
    "nav.talent": "Créer CV",
    "nav.companies": "Entreprises",
    "nav.features": "Avantages",
    "nav.faq": "FAQ",
    "nav.login": "Connexion",
    "nav.getStarted": "Commencer",
    "nav.hiring": "Vous recrutez ?",
    "nav.joinTalent": "Créer un CV",
    "nav.appearance": "Apparence",
    "nav.language": "Langue",
    "nav.mode.dark": "Sombre",
    "nav.mode.light": "Clair",
    "nav.back": "Retour",
    "nav.logout": "Se déconnecter",
    
    // Hero
    "hero.badge": "Générateur de CV Professionnel",
    "hero.title.prefix": "Votre carrière...",
    "hero.title.highlight": "Commence par la transparence.",
    "hero.description": "Créez un CV professionnel en quelques minutes. Connectez-vous avec les meilleures entreprises dans un environnement sécurisé et vérifié.",
    "hero.cta.find": "Explorer les offres",
    "hero.cta.join": "Créer un CV Gratuit",
    "hero.cta.login": "Se connecter",
    "hero.card.verified": "Compatible ATS",
    "hero.card.matchScore": "Score ATS",
    "hero.card.exp": "Exp",
    "hero.card.projects": "Projets",
    "hero.mock.role": "Profil Professionnel",
    "hero.mock.name": "Amine Amrani",
    "hero.mock.notification": "Alerte Emploi",
    "hero.mock.crew": "Équipe Recrutement",
    "hero.mock.welcome": "\"Votre CV a passé la sélection initiale ! Nous aimerions planifier un entretien.\"",
    "hero.mock.preference": "Rôle",
    "hero.mock.remote": "Télétravail",
    "hero.mock.location": "Lieu",
    "hero.mock.city": "Alger, DZ",
    "hero.mock.status": "Disponibilité",
    "hero.mock.available": "Immédiate",

    // Features
    "features.title.prefix": "Pourquoi",
    "features.title.highlight": "Traviit ?",
    "features.description": "Des outils avancés pour un parcours professionnel plus intelligent.",
    "features.1.title": "Tableau de bord de carrière",
    "features.1.desc": "Suivez le nombre de vues de votre CV et quels responsables RH s'intéressent à votre profil.",
    "features.2.title": "Environnement sécurisé",
    "features.2.desc": "Votre confidentialité est notre priorité ; vos données sont chiffrées et visibles uniquement par les employeurs vérifiés.",
    "features.3.title": "Connexion directe",
    "features.3.desc": "Connectez-vous directement avec les responsables du recrutement des grandes entreprises sans intermédiaires.",
    "features.4.title": "Correspondance Intelligente",
    "features.4.desc": "Nos algorithmes mettent en avant votre profil auprès des entreprises recherchant spécifiquement vos compétences.",

    // Timeline
    "timeline.badge": "Comment ça marche",
    "timeline.title": "Comment fonctionne Traviit ?",
    "timeline.desc": "Choisissez votre parcours.",
    "timeline.toggle.seeker": "Chercheur d'emploi",
    "timeline.toggle.recruiter": "Recruteur (RH)",
    
    // Seeker Steps
    "timeline.seeker.title": "Développez votre parcours professionnel",
    "timeline.seeker.step1.title": "Remplissez vos données",
    "timeline.seeker.step1.desc": "Entrez votre expérience et vos compétences, et notre éditeur intelligent les mettra en forme automatiquement.",
    "timeline.seeker.step2.title": "Choisissez un modèle",
    "timeline.seeker.step2.desc": "Choisissez parmi une variété de modèles professionnels adaptés à votre spécialisation.",
    "timeline.seeker.step3.title": "Téléchargez et postulez",
    "timeline.seeker.step3.desc": "Téléchargez votre version prête à imprimer et ouvrez de nouvelles portes pour votre avenir professionnel dès aujourd'hui.",

    // Recruiter Steps
    "timeline.recruiter.title": "Boostez l'efficacité de votre organisation",
    "timeline.recruiter.step1.title": "Filtrage Intelligent",
    "timeline.recruiter.step1.desc": "Notre système analyse les compétences des candidats et les fait correspondre à vos besoins avec une précision de 95%.",
    "timeline.recruiter.step2.title": "Gestion du Recrutement",
    "timeline.recruiter.step2.desc": "Communiquez avec les candidats, organisez des entretiens et prenez des décisions d'embauche via un tableau de bord intégré.",
    "timeline.recruiter.step3.title": "CV Standardisés",
    "timeline.recruiter.step3.desc": "Fini les formats dispersés ; tous les fichiers arrivent dans un format professionnel unifié pour une comparaison rapide.",

    // Stats
    "stats.jobs.total": "Emplois Plein Temps",
    "stats.jobs.students": "Opportunités Étudiants",
    "stats.community": "Membres de la communauté",
    "stats.active_hr": "RH en poste active",
    "stats.whatsapp.title": "Rejoignez la communauté d'élite",
    "stats.whatsapp.desc": "Recevez des alertes emploi instantanées sur WhatsApp. Choisissez le canal adapté à votre étape de carrière.",
    "stats.btn.fulltime": "Recrutement Traviit",
    "stats.btn.student": "Traviit",

    // Dashboard
    "dashboard.whoViewed": "Correspondances",
    "dashboard.realTime": "EN DIRECT",
    "dashboard.unlocked": "Forte Correspondance",
    "dashboard.pending": "En revue",
    "dashboard.denied": "Vu",
    "dashboard.tooltip": "Contenu optimisé ATS",
    "dashboard.title": "Base de données en temps réel",
    "dashboard.desc": "Plus besoin d'appeler des candidats déjà embauchés. Traviit priorise les profils 'Disponibles immédiatement'.",
    "dashboard.list1": "+2 500 Profils Actifs le mois dernier.",
    "dashboard.list2": "+45 Entreprises Vérifiées recrutent actuellement.",
    "dashboard.list3": "Taux de réponse aux entretiens 3x supérieur.",
    "dashboard.cta": "Commencez à bâtir votre carrière",
    "dashboard.mock.company1": "Prophex",
    "dashboard.mock.company2": "Techno",
    "dashboard.mock.company3": "CPH",
    
    "testimonials.title": "Rejoignez le futur du recrutement",
    "testimonials.desc": "De vrais avis de talents ayant trouvé leur voie et de recruteurs ayant bâti leurs équipes de rêve.",
    "testimonials.1.text": "\"J'ai utilisé le générateur de CV gratuit et j'ai eu 3 entretiens la première semaine. Le modèle compatible ATS fonctionne vraiment !\"",
    "testimonials.1.role": "Ingénieur Logiciel",
    "testimonials.2.text": "\"Simple, rapide et professionnel. Je n'ai pas eu à me soucier de la mise en forme. Hautement recommandé.\"",
    "testimonials.2.role": "Spécialiste Marketing",
    "testimonials.3.text": "\"La connexion directe aux recruteurs change la donne. J'ai évité les formulaires de candidature interminables.\"",
    "testimonials.3.role": "Chef de Projet",
    "testimonials.4.text": "\"Enfin une plateforme en Algérie qui comprend ce que recherchent les entreprises internationales.\"",
    "testimonials.4.role": "Analyste de Données",
    
    "cta.title": "Prêt pour votre prochaine étape ?",
    "cta.desc": "Transformez votre expérience en un CV professionnel et obtenez une correspondance instantanée avec le job de vos rêves.",
    "cta.join": "Créer CV Maintenant",
    "cta.contact": "Contacter le support",

    "recruiter.landing.title": "Vous cherchez le talent parfait ?",
    "recruiter.landing.desc": "Parcourez nos bases de données mises à jour et utilisez des outils de filtrage intelligents pour trouver la bonne compétence en quelques secondes.",
    "recruiter.landing.cta": "Rejoindre comme Recruteur",
    "recruiter.landing.verified": "Données Vérifiées",
    "recruiter.landing.check": "Filtrage Intelligent",

    "faq.title": "Questions Fréquemment Posées (FAQ)",
    "faq.q1": "Puis-je télécharger mon CV et l'utiliser en dehors de la plateforme ?",
    "faq.a1": "Oui, Traviit vous permet de télécharger votre CV dans des formats professionnels prêts à l'impression ou à l'envoi par email à tout moment.",
    "faq.q2": "Puis-je mettre à jour mes données plus tard ?",
    "faq.a2": "Certainement, votre fichier est sauvegardé et vous pouvez le modifier à tout moment et depuis n'importe quel appareil.",
    "faq.q3": "Comment Traviit garantit-il que mon profil atteint les recruteurs ?",
    "faq.a3": "Une fois votre profil complété à 100%, votre nom apparaît automatiquement dans les résultats de recherche intelligente pour les entreprises recherchant vos compétences.",
    "faq.q4": "Traviit me garantit-il un emploi ?",
    "faq.a4": "Nous vous garantissons un CV professionnel et une visibilité intelligente auprès des grandes entreprises, ce qui augmente considérablement vos chances d'embauche par rapport aux méthodes traditionnelles.",
    "faq.q5": "Mes données personnelles sont-elles protégées ?",
    "faq.a5": "Absolument. Traviit respecte les normes les plus strictes de protection des données. Vos coordonnées ne sont affichées qu'aux entreprises auxquelles vous postulez ou que vous autorisez.",

    "contact.title": "Contactez-nous",
    "contact.desc": "Des questions ? Nous sommes là pour vous aider.",
    "contact.emailUs": "Envoyez-nous un email",
    "contact.visitUs": "Visitez-nous",
    "contact.form.name": "Votre Nom",
    "contact.form.email": "Votre Email",
    "contact.form.subject": "Sujet",
    "contact.form.message": "Message",
    "contact.btn.send": "Envoyer le message",

    "footer.privacy": "Politique de Confidentialité",
    "footer.transparency": "Conditions d'utilisation",
    "footer.linkedin": "LinkedIn",
    "footer.facebook": "Facebook",
    "footer.instagram": "Instagram",
    "footer.copyright": "© 2024 Traviit. Tous droits réservés.",
    "footer.madeFor": "Fait pour l'Algérie",

    "login.title": "Bon retour",
    "login.subtitle": "Entrez vos identifiants pour accéder à votre tableau de bord.",
    "login.noAccount": "Pas encore de compte ?",
    "login.register": "S'inscrire",
    "login.submit": "Connexion",
    
    "recruiter.login.title": "Connexion Recruteur",
    "recruiter.login.subtitle": "Accédez à votre vivier de talents.",
    "recruiter.login.cta": "Se connecter",
    "recruiter.login.new": "Nouveau sur Traviit ?",
    "recruiter.login.register": "Inscrire l'entreprise",
    
    "recruiter.form.corporate": "Accès Entreprise",
    "recruiter.form.title": "Inscription Recruteur",
    "recruiter.form.subtitle": "Créez un compte pour accéder aux talents algériens vérifiés.",
    "recruiter.form.section.company": "Détails de l'entreprise",
    "recruiter.form.section.rep": "Détails du représentant",
    "recruiter.form.section.security": "Sécurité",
    "recruiter.form.companyName": "Nom de l'entreprise",
    "recruiter.form.industry": "Secteur",
    "recruiter.form.website": "Site Web (Optionnel)",
    "recruiter.form.fullName": "Nom Complet",
    "recruiter.form.position": "Titre du poste",
    "recruiter.form.workEmail": "Email Professionnel",
    "recruiter.form.phone": "Numéro de téléphone",
    "recruiter.form.password": "Mot de passe",
    "recruiter.form.confirmPassword": "Confirmer le mot de passe",
    "recruiter.form.submit": "Enregistrer l'organisation",
    "recruiter.form.portal": "Portail Entreprise",
    
    "dash.menu.profile": "Vue d'ensemble",
    "dash.menu.cvs": "Mes CVs",
    "dash.section.identity": "Identité",
    "dash.section.exp": "Expérience",
    "dash.section.edu": "Éducation",
    "dash.section.skills": "Compétences",
    "dash.section.admin": "Admin",
    "dash.cv.choose": "Choisir le modèle",
    "dash.cv.modern": "Moderne",
    "dash.cv.classic": "Classique",
    "dash.cv.creative": "Créatif",
    "dash.cv.download": "Télécharger l'image",

    "dash.search.placeholder": "Rechercher par poste ou compétence...",
    "dash.filter.reset": "Réinitialiser les filtres",
    "dash.filter.showAdvanced": "Afficher les filtres avancés",
    "dash.filter.hideAdvanced": "Masquer les filtres avancés",
    "dash.discovery.title": "Découverte de Talents",
    "dash.discovery.subtitle": "{count} candidats vérifiés correspondant à vos critères.",
    "dash.menu.search": "Recherche de Talents",
    "dash.menu.saved": "Enregistrés",
    "dash.menu.jobs": "Mes Offres",
    "dash.menu.settings": "Paramètres",
    
    "cand.matchScore": "Score de correspondance",
    "cand.salary": "Prétention salariale",
    "cand.availability": "Disponibilité",
    "cand.about": "À propos du candidat",
    "cand.skills": "Compétences techniques",
    "cand.history": "Historique professionnel",
    "cand.education": "Éducation",
    "cand.profile": "Profil Candidat",
    "cand.verifiedEdu": "Qualification Vérifiée",
    "cand.yearsExp": "Années d'exp.",
    
    "btn.backToSearch": "Retour à la recherche",
    "btn.viewProfile": "Voir le profil",
    "btn.viewCV": "Voir le CV",
    "btn.whatsapp": "WhatsApp",
    "btn.save": "Sauvegarder",
    "btn.saved": "Enregistré",
    
    "filter.experience": "Expérience",
    "filter.education": "Éducation",
    "filter.availability": "Disponibilité",
    "filter.workType": "Type de travail",
    "filter.industry": "Secteur",
    "filter.datePosted": "Date de publication",
    "filter.language": "Langue",

    "wizard.step.identity": "Infos Personnelles",
    "wizard.step.target": "Objectif Carrière",
    "wizard.step.experience": "Expérience",
    "wizard.step.education": "Éducation",
    "wizard.step.admin": "Logistique",
    "wizard.step.review": "Révision",
    "wizard.step.desc.1": "Commencez par vérifier vos détails personnels.",
    "wizard.step.desc.2": "Définissez vos objectifs professionnels et préférences.",
    "wizard.step.desc.3": "Présentez votre parcours et vos réalisations.",
    "wizard.step.desc.4": "Listez votre parcours académique et vos diplômes.",
    "wizard.step.desc.5": "Détails administratifs et logistiques.",
    "wizard.step.desc.6": "Vérifiez vos informations avant soumission.",

    "form.firstName": "Prénom",
    "form.lastName": "Nom",
    "form.aboutMe": "À propos de moi",
    "form.aboutMe.placeholder": "Décrivez-vous brièvement...",
    "form.dob": "Date de naissance",
    "form.pob": "Lieu de naissance",
    "form.gender": "Genre",
    "form.nationality": "Nationalité",
    "form.gender.male": "Homme",
    "form.gender.female": "Femme",

    "form.phone": "Numéro de téléphone",
    "form.email": "Adresse Email",
    "form.website": "Site Web",
    "form.linkedIn": "LinkedIn",
    "form.otherLink": "Autre lien (Portfolio/Blog)",
    "form.github": "GitHub",
    "form.whatsapp": "Numéro WhatsApp",
    "form.whatsapp.placeholder": "+213...",
    "form.whatsapp.hint": "Doit commencer par +213 suivi de 5, 6 ou 7...",
    "form.viber": "Viber",
    "form.telegram": "Telegram",
    "form.toggle.messaging": "Applications de messagerie",
    "form.toggle.socials": "Liens sociaux",

    "form.address.type": "Type d'adresse",
    "form.address.street": "Adresse",
    "form.address.zip": "Code Postal",
    "form.address.city": "Wilaya (Ville)",
    "form.address.city.placeholder": "Sélectionner Wilaya",
    "form.address.country": "Pays",
    "form.address.home": "Domicile",
    "form.address.work": "Travail",
    "form.address.other": "Autre",

    "form.targetJobTitle": "Titre du poste souhaité",
    "form.targetJobTitle.placeholder": "ex: Comptable, Ingénieur Logiciel",
    "form.targetLocation": "Lieu souhaité (Wilaya)",
    "form.targetLocation.placeholder": "Sélectionner Wilaya préférée",
    "form.targetCompany": "Entreprise cible (Optionnel)",
    "form.careerStage": "Stade de carrière",
    "form.employmentType": "Type d'emploi",
    "form.careerGoal": "Objectif Professionnel",
    "form.careerGoal.placeholder": "Décrivez vos objectifs de carrière...",
    "form.toggle.company": "Entreprise cible",
    "form.toggle.goal": "Objectif de carrière",
    "form.noticePeriod": "Préavis",
    "form.noticePeriod.placeholder": "Sélectionner disponibilité",
    "form.notice.immediate": "Immédiat",
    "form.notice.1month": "1 Mois",
    "form.notice.3months": "3 Mois",
    
    "form.stage.student": "Étudiant",
    "form.stage.intern": "Stagiaire",
    "form.stage.fresh_graduate": "Nouveau Diplômé",
    "form.stage.junior": "Junior (1-3 ans)",
    "form.stage.mid_level": "Intermédiaire (3-5 ans)",
    "form.stage.senior": "Sénior (5+ ans)",
    "form.stage.executive": "Exécutif",

    "form.emp.full_time": "Plein temps",
    "form.emp.part_time": "Temps partiel",
    "form.emp.freelance": "Freelance",
    "form.emp.internship": "Stage",
    "form.emp.temporary": "Temporaire",
    "form.emp.contract": "Contrat",

    "form.nationalService": "Service National",
    "form.drivingLicense": "Permis de conduire",
    "form.drivingPermits.placeholder": "Sélectionner permis (ex: B, C...)",
    "form.additionalInfo": "Informations Complémentaires",
    "form.photoUrl": "URL Photo",

    "form.ns.exempted": "Exempté",
    "form.ns.postponed": "Ajourné",
    "form.ns.completed": "Accompli",
    "form.ns.not_concerned": "Non concerné",

    "form.exp.title": "Expérience Professionnelle",
    "form.exp.add": "Ajouter Expérience",
    "form.jobTitle": "Titre du poste",
    "form.company": "Nom de l'entreprise",
    "form.location": "Lieu",
    "form.locationType": "Type de lieu",
    "form.loc.remote": "Télétravail",
    "form.loc.hybrid": "Hybride",
    "form.loc.onsite": "Sur site",
    "form.description": "Résumé du rôle (Optionnel)",
    "form.description.placeholder": "Brève description du rôle...",
    "form.skillsUsed": "Technologies/Compétences (Optionnel)",
    "form.skillsUsed.placeholder": "ex: React, Excel, Gestion (séparés par virgule)",
    "form.activity": "Activité de l'entreprise",
    "form.startDate": "Date de début",
    "form.endDate": "Date de fin",
    "form.current": "Je travaille ici actuellement",
    "form.achievements": "Réalisations Clés (Une par ligne)",
    "form.achievements.placeholder": "- Augmentation des ventes de 20%\n- Gestion d'une équipe de 5 personnes",
    "form.exp.none": "Aucune expérience ajoutée.",

    "form.edu.title": "Éducation",
    "form.edu.add": "Ajouter Éducation",
    "form.degree": "Diplôme / Qualification",
    "form.institution": "Institution / Université",
    "form.gradYear": "Année d'obtention",
    "form.edu.none": "Aucune éducation ajoutée.",

    "form.skills.hard": "Compétences Techniques (Hard Skills)",
    "form.skills.soft": "Compétences Douces (Soft Skills)",
    "form.skills.placeholder": "Tapez et appuyez sur Entrée...",
    "form.skills.none": "Aucune compétence sélectionnée.",

    "form.lang.title": "Langues",
    "form.lang.add": "Ajouter Langue",
    "form.lang.name": "Langue",
    "form.lang.name.placeholder": "ex: Anglais, Arabe",
    "form.lang.level": "Niveau",
    "form.lang.native": "Langue maternelle",
    "form.lang.beginner": "Débutant",
    "form.lang.intermediate": "Intermédiaire",
    "form.lang.good": "Bon",
    "form.lang.advanced": "Avancé",

    "form.admin.title": "Administratif & Logistique",
    "form.accommodation": "Hébergement requis ?",
    "form.smoking": "Fumeur ?",
    "form.ref.name": "Nom du superviseur",
    "form.ref.phone": "Téléphone du superviseur",
    "form.ref.rel": "Relation",

    "btn.next": "Suivant",
    "btn.back": "Retour",
    "btn.preview": "Aperçu CV",
    "btn.submit": "Soumettre",
    "btn.cancel": "Annuler",
    "btn.share": "Partager CV",
    "share.text": "Voir mon profil professionnel vérifié sur Traviit.",
    "btn.copy": "Copier lien",
    "btn.copied": "Copié !",
    "msg.required": "Requis",
    "msg.minSkills": "Veuillez ajouter au moins 3 compétences techniques.",
    "msg.minLangs": "Veuillez ajouter au moins 2 langues.",
    "msg.invalidWhatsApp": "Invalide. Doit commencer par +213 suivi de 5, 6 ou 7 et 8 chiffres.",
    "msg.invalidEmail": "Veuillez entrer une adresse email valide.",
    "msg.passwordMismatch": "Les mots de passe ne correspondent pas.",
    "msg.passwordWeak": "Le mot de passe doit contenir au moins 6 caractères.",
    "msg.saveEntry": "Veuillez sauvegarder ou annuler l'entrée en cours",
    "msg.done": "Tout est prêt !",
    "msg.done.desc": "Votre profil est en cours de chiffrement. Vous recevrez bientôt un email de vérification.",
    "dash.welcome": "Bienvenue",
    "dash.viewCV": "Voir CV",
    "dash.editProfile": "Modifier Profil",
    "dash.status": "Statut Profil",
    "dash.status.active": "Actif",
    "dash.stats.views": "Vues du Profil",
    "dash.stats.appears": "Apparitions Recherche",
    "dash.stats.requests": "Demandes de Contact",
    "modal.signup.title": "Sécurisez votre compte",
    "modal.signup.desc": "Définissez un mot de passe pour accéder à votre tableau de bord plus tard. Vos coordonnées sont déjà vérifiées.",
    "form.password": "Créer mot de passe",
    "form.confirmPassword": "Confirmer mot de passe",
    "btn.completeSignup": "Terminer l'inscription",

    "common.none": "Aucun",
    "common.present": "Présent",
    "common.comingSoon": "Bientôt",
    "common.years": "Ans",
    "common.month": "Mois",
    "common.months": "Mois",
    "common.immediate": "Immédiat",

    "doc.settings": "Paramètres du document CV",
    "doc.lang": "Langue du document généré",
    "review.identity": "Identité",
    "review.target": "Cible",
    "review.skills": "Compétences & Langues",
    "review.admin": "Admin & Divers",
    "review.generated": "Généré par Traviit",
    "review.mode": "Mode Révision",
    "review.desc": "Vérifiez vos détails avant de finaliser.",
    "terms.label": "Je confirme que les informations fournies sont exactes et j'accepte les",
    "terms.use": "Conditions d'utilisation",
    "terms.privacy": "Politique de confidentialité",

    "job.post.new": "Publier une offre",
    "job.post.title": "Titre du poste",
    "job.post.location": "Lieu",
    "job.post.type": "Type de poste",
    "job.post.salary": "Fourchette salariale",
    "job.post.desc": "Description du poste",
    "job.post.req": "Exigences",
    "job.post.submit": "Publier",
    "job.post.success": "Offre publiée avec succès !",
    "job.list.active": "Offres actives",
    "job.list.noJobs": "Aucune offre active. Publiez votre première offre !",
    "job.list.applicants": "Candidats",

    // Month translations
    "month.01": "Janvier",
    "month.02": "Février",
    "month.03": "Mars",
    "month.04": "Avril",
    "month.05": "Mai",
    "month.06": "Juin",
    "month.07": "Juillet",
    "month.08": "Août",
    "month.09": "Septembre",
    "month.10": "Octobre",
    "month.11": "Novembre",
    "month.12": "Décembre",
    "year.present": "Présent"
};
