
import React from 'react';
import { UnifiedCV } from '../../types/forms';
import { useLanguage } from '../../context/LanguageContext';

interface CVTemplateProps {
  cvData: UnifiedCV;
  t: (key: string) => string;
}

const getLabels = (docLang: 'en' | 'ar' | 'fr', t: (k: string) => string) => {
    const labels = {
       en: {
           exp: "WORK EXPERIENCE",
           edu: "EDUCATION",
           skills: "SKILLS & INTERESTS",
           projects: "PROJECT EXPERIENCE",
           lang: "LANGUAGES",
           summary: "PROFESSIONAL SUMMARY",
           additional: "ADDITIONAL INFORMATION",
           skillsLabel: "Skills:",
           driving: "Driving License:",
           military: "National Service:"
       },
       fr: {
           exp: "EXPÉRIENCE PROFESSIONNELLE",
           edu: "ÉDUCATION",
           skills: "COMPÉTENCES & INTÉRÊTS",
           projects: "PROJETS",
           lang: "LANGUES",
           summary: "RÉSUMÉ PROFESSIONNEL",
           additional: "INFORMATIONS COMPLÉMENTAIRES",
           skillsLabel: "Compétences:",
           driving: "Permis de conduire:",
           military: "Service National:"
       },
       ar: {
           exp: "الخبرة المهنية",
           edu: "التعليم",
           skills: "المهارات والاهتمامات",
           projects: "المشاريع",
           lang: "اللغات",
           summary: "ملخص مهني",
           additional: "معلومات إضافية",
           skillsLabel: "المهارات:",
           driving: "رخصة القيادة:",
           military: "الخدمة الوطنية:"
       }
    };
    return labels[docLang] || labels.en;
};

const TraviitFooter = () => (
    <div className="absolute bottom-4 left-0 right-0 flex justify-center items-center print:flex">
        <a href="https://traviit.com" className="flex items-center gap-1.5 px-3 py-1 bg-white/90 rounded-full border border-gray-100 shadow-sm text-[10px] text-gray-400 font-semibold tracking-wide uppercase hover:text-electric-blue hover:border-electric-blue/30 transition-colors no-underline">
            <span className="w-2 h-2 rounded-full bg-electric-blue/50"></span>
            Generated by Traviit
        </a>
    </div>
);

export const TemplateModern: React.FC<CVTemplateProps> = ({ cvData, t }) => {
  const activeCvLabels = getLabels(cvData.documentLanguage, t);
  const isRtl = cvData.documentLanguage === 'ar';

  return (
    <div 
        id="cv-document" 
        dir={isRtl ? 'rtl' : 'ltr'}
        className={`bg-white text-gray-800 p-0 mx-auto w-[210mm] h-[297mm] relative flex flex-col ${isRtl ? 'font-cairo' : 'font-sans'} shadow-2xl overflow-hidden`}
    >
        {/* Header Section */}
        <div className="bg-slate-900 text-white p-12 pb-10">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6">
                <div>
                    <h1 className="text-4xl md:text-5xl font-extrabold uppercase tracking-tight leading-none mb-2">
                        {cvData.personalInfo.firstName} <span className="text-electric-blue">{cvData.personalInfo.lastName}</span>
                    </h1>
                    <p className="text-xl text-slate-300 font-medium tracking-wide uppercase">{cvData.targetJob.title}</p>
                </div>
                
                <div className={`text-sm text-slate-400 space-y-1 ${isRtl ? 'md:text-left' : 'md:text-right'}`}>
                    <div className="flex items-center gap-2 justify-end">
                        <span dir="ltr">{cvData.personalInfo.phoneNumber}</span>
                        <span className="material-symbols-outlined text-sm text-electric-blue">call</span>
                    </div>
                    <div className="flex items-center gap-2 justify-end">
                        <span>{cvData.personalInfo.email}</span>
                        <span className="material-symbols-outlined text-sm text-electric-blue">mail</span>
                    </div>
                    <div className="flex items-center gap-2 justify-end">
                        <span>{cvData.personalInfo.address.city}, {cvData.personalInfo.address.country}</span>
                        <span className="material-symbols-outlined text-sm text-electric-blue">location_on</span>
                    </div>
                </div>
            </div>
        </div>

        {/* Main Content Grid */}
        <div className="flex-1 flex flex-col md:flex-row overflow-hidden">
            
            {/* Left Column (Main) */}
            <div className="md:w-2/3 p-10 space-y-8 order-2 md:order-1 overflow-y-hidden">
                
                {/* Summary */}
                {(cvData.personalInfo.aboutMe || cvData.targetJob.careerGoal) && (
                    <div className="mb-8">
                        <h3 className="text-sm font-bold uppercase text-slate-900 tracking-widest border-b-2 border-electric-blue w-fit pb-1 mb-4">
                            {activeCvLabels.summary}
                        </h3>
                        <p className="text-sm leading-relaxed text-slate-600 text-justify">
                            {cvData.personalInfo.aboutMe || cvData.targetJob.careerGoal}
                        </p>
                    </div>
                )}

                {/* Experience */}
                {cvData.professionalExperiences.length > 0 && (
                    <div>
                        <h3 className="text-sm font-bold uppercase text-slate-900 tracking-widest border-b-2 border-electric-blue w-fit pb-1 mb-6">
                            {activeCvLabels.exp}
                        </h3>
                        <div className="space-y-8 border-l-2 border-slate-100 ml-1.5 pl-6 relative">
                            {cvData.professionalExperiences.map((exp, i) => (
                                <div key={i} className="relative break-inside-avoid">
                                    <span className="absolute -left-[31px] top-1.5 w-3 h-3 bg-white border-2 border-electric-blue rounded-full"></span>
                                    <div className="flex flex-col mb-2">
                                        <h4 className="font-bold text-lg text-slate-900">{exp.jobTitle}</h4>
                                        <div className="flex justify-between items-center text-sm mb-1">
                                            <div className="flex items-center gap-2">
                                                <span className="font-bold text-electric-blue">{exp.companyName}</span>
                                                {exp.employmentType && (
                                                    <span className="text-slate-400 text-xs border-l border-slate-300 pl-2 ml-1">
                                                        {t(`form.emp.${exp.employmentType}`)}
                                                    </span>
                                                )}
                                                {exp.locationType && (
                                                    <span className="text-slate-400 text-xs bg-slate-100 px-1.5 rounded">
                                                        {t(`form.loc.${exp.locationType}`)}
                                                    </span>
                                                )}
                                            </div>
                                            <span className="text-slate-500 italic" dir="ltr">
                                                {exp.period.start} — {exp.period.isCurrent ? (isRtl ? 'حاضر' : 'Present') : exp.period.end}
                                            </span>
                                        </div>
                                        {exp.description && (
                                            <p className="text-sm text-slate-600 mb-2 italic">
                                                {exp.description}
                                            </p>
                                        )}
                                    </div>
                                    {exp.keyAchievements.length > 0 && (
                                        <ul className={`list-disc list-outside text-sm text-slate-600 space-y-1.5 ${isRtl ? 'mr-4' : 'ml-4'}`}>
                                            {exp.keyAchievements.map((ach, j) => (
                                                <li key={j} className="marker:text-slate-400">{ach}</li>
                                            ))}
                                        </ul>
                                    )}
                                    {exp.skillsUsed && exp.skillsUsed.length > 0 && (
                                        <div className="mt-3 flex flex-wrap gap-1.5">
                                            {exp.skillsUsed.map((skill, k) => (
                                                <span key={k} className="px-1.5 py-0.5 bg-slate-100 text-[10px] text-slate-500 rounded border border-slate-200">
                                                    {skill}
                                                </span>
                                            ))}
                                        </div>
                                    )}
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {/* Education */}
                {cvData.education.length > 0 && (
                    <div>
                        <h3 className="text-sm font-bold uppercase text-slate-900 tracking-widest border-b-2 border-electric-blue w-fit pb-1 mb-6">
                            {activeCvLabels.edu}
                        </h3>
                        <div className="grid gap-4">
                            {cvData.education.map((edu, i) => (
                                <div key={i} className="bg-slate-50 p-4 rounded-lg border-l-4 border-slate-200 break-inside-avoid">
                                    <div className="flex justify-between items-start">
                                        <div>
                                            <h4 className="font-bold text-slate-900">{edu.qualification}</h4>
                                            <p className="text-sm text-slate-600">{edu.institution}</p>
                                        </div>
                                        <span className="text-xs font-bold bg-white px-2 py-1 rounded shadow-sm text-slate-500">
                                            {edu.graduationYear}
                                        </span>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                )}
            </div>

            {/* Right Column (Sidebar) */}
            <div className="md:w-1/3 bg-slate-50 p-10 border-l border-slate-100 order-1 md:order-2 overflow-y-hidden">
                <div className="space-y-8 sticky top-10">
                    
                    {/* Skills */}
                    <div>
                        <h3 className="text-xs font-bold uppercase text-slate-400 tracking-widest mb-4">
                            {activeCvLabels.skills}
                        </h3>
                        <div className="flex flex-wrap gap-2">
                            {cvData.skills.hardSkills.map((s, i) => (
                                <span key={i} className="px-2 py-1 bg-white border border-slate-200 rounded text-xs font-semibold text-slate-700 shadow-sm">
                                    {s}
                                </span>
                            ))}
                        </div>
                    </div>

                    {/* Languages */}
                    <div>
                        <h3 className="text-xs font-bold uppercase text-slate-400 tracking-widest mb-4">
                            {activeCvLabels.lang}
                        </h3>
                        <div className="space-y-3">
                            {cvData.languages.map((l, i) => (
                                <div key={i} className="flex justify-between items-center text-sm border-b border-slate-200 pb-2 last:border-0">
                                    <span className="font-bold text-slate-700">{l.language}</span>
                                    <span className="text-xs text-slate-500 uppercase">{l.level}</span>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Soft Skills */}
                    {cvData.skills.softSkills.length > 0 && (
                        <div>
                            <h3 className="text-xs font-bold uppercase text-slate-400 tracking-widest mb-4">
                                {t('form.skills.soft')}
                            </h3>
                            <ul className="text-sm text-slate-600 space-y-2 list-disc list-inside marker:text-electric-blue">
                                {cvData.skills.softSkills.map((s, i) => (
                                    <li key={i}>{s}</li>
                                ))}
                            </ul>
                        </div>
                    )}

                    {/* Additional Info */}
                    {(cvData.additionalInfo.drivingPermits.length > 0 || cvData.additionalInfo.nationalServiceStatus !== 'not_concerned') && (
                        <div>
                            <h3 className="text-xs font-bold uppercase text-slate-400 tracking-widest mb-4">
                                {activeCvLabels.additional}
                            </h3>
                            <ul className="text-sm space-y-2 text-slate-600">
                                {cvData.additionalInfo.drivingPermits.length > 0 && (
                                    <li className="flex items-center gap-2">
                                        <span className="material-symbols-outlined text-base">directions_car</span>
                                        <span>Permits: {cvData.additionalInfo.drivingPermits.join(', ')}</span>
                                    </li>
                                )}
                                {cvData.additionalInfo.nationalServiceStatus !== 'not_concerned' && (
                                    <li className="flex items-center gap-2">
                                        <span className="material-symbols-outlined text-base">military_tech</span>
                                        <span>{t(`form.ns.${cvData.additionalInfo.nationalServiceStatus}`)}</span>
                                    </li>
                                )}
                            </ul>
                        </div>
                    )}

                </div>
            </div>
        </div>
        <TraviitFooter />
    </div>
  );
};

export const TemplateClassic: React.FC<CVTemplateProps> = ({ cvData, t }) => {
    const activeCvLabels = getLabels(cvData.documentLanguage, t);
    const isRtl = cvData.documentLanguage === 'ar';
  
    return (
      <div 
          id="cv-document" 
          dir={isRtl ? 'rtl' : 'ltr'}
          className={`bg-white text-black p-12 md:p-14 mx-auto w-[210mm] h-[297mm] relative ${isRtl ? 'font-cairo' : 'font-serif'} shadow-2xl overflow-hidden`}
      >
          {/* Header */}
          <div className="text-center mb-8">
              <h1 className="text-3xl font-bold mb-1 tracking-wide">{cvData.personalInfo.firstName} {cvData.personalInfo.lastName}</h1>
              <div className="text-[13px] flex flex-wrap justify-center gap-1 text-black">
                  <span className="hover:underline">{cvData.personalInfo.email}</span>
                  {cvData.personalInfo.socialMedia.linkedIn && (
                      <>
                        <span>|</span>
                        <span className="hover:underline">{cvData.personalInfo.socialMedia.linkedIn.replace(/^https?:\/\//, '')}</span>
                      </>
                  )}
                  {cvData.personalInfo.socialMedia.github && (
                      <>
                        <span>|</span>
                        <span className="hover:underline">{cvData.personalInfo.socialMedia.github.replace(/^https?:\/\//, '')}</span>
                      </>
                  )}
                  {cvData.personalInfo.phoneNumber && (
                      <>
                        <span>|</span>
                        <span dir="ltr">{cvData.personalInfo.phoneNumber}</span>
                      </>
                  )}
              </div>
          </div>
  
          <div className="flex flex-col gap-6">
            
            {/* Experience */}
            {cvData.professionalExperiences.length > 0 && (
                <div>
                    <h3 className="text-sm font-bold uppercase border-b border-black mb-3 pb-0.5">{activeCvLabels.exp}</h3>
                    <div className="space-y-4">
                        {cvData.professionalExperiences.map((exp, i) => (
                            <div key={i} className="break-inside-avoid">
                                <div className="flex justify-between items-baseline text-sm">
                                    <span className="font-bold">{exp.companyName}</span>
                                    <span className="font-bold">{exp.companyLocation}</span>
                                </div>
                                <div className="flex justify-between items-baseline text-sm italic mb-1">
                                    <span>{exp.jobTitle}</span>
                                    <span dir="ltr">
                                        {exp.period.start} - {exp.period.isCurrent ? (isRtl ? 'حاضر' : 'Present') : exp.period.end}
                                    </span>
                                </div>
                                
                                {exp.keyAchievements.length > 0 && (
                                    <ul className={`list-disc list-outside text-[13px] leading-relaxed pl-5 ${isRtl ? 'pr-5 pl-0' : ''}`}>
                                        {exp.keyAchievements.map((ach, j) => (
                                            <li key={j}>{ach}</li>
                                        ))}
                                    </ul>
                                )}
                            </div>
                        ))}
                    </div>
                </div>
            )}
    
            {/* Education */}
            {cvData.education.length > 0 && (
                <div>
                    <h3 className="text-sm font-bold uppercase border-b border-black mb-3 pb-0.5">{activeCvLabels.edu}</h3>
                    <div className="space-y-2">
                        {cvData.education.map((edu, i) => (
                            <div key={i} className="break-inside-avoid">
                                <div className="flex justify-between items-baseline text-sm">
                                    <span className="font-bold">{edu.institution}</span>
                                    <span className="font-bold">{cvData.personalInfo.address.city}, {cvData.personalInfo.address.country}</span>
                                </div>
                                <div className="text-sm italic">
                                    {edu.qualification}
                                    {edu.graduationYear && `, ${edu.graduationYear}`}
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            )}
    
            {/* Skills & Interests */}
            <div>
                <h3 className="text-sm font-bold uppercase border-b border-black mb-3 pb-0.5">{activeCvLabels.skills}</h3>
                <div className="text-sm">
                    <p>
                        <span className="font-bold">{activeCvLabels.skillsLabel} </span>
                        {cvData.skills.hardSkills.join(', ')}
                        {cvData.languages.length > 0 && (
                            <>
                                <span className="mx-2">|</span>
                                <span className="font-bold">{activeCvLabels.lang}: </span>
                                {cvData.languages.map(l => l.language).join(', ')}
                            </>
                        )}
                    </p>
                </div>
            </div>

            {/* Additional Info if needed */}
            {cvData.additionalInfo.drivingPermits.length > 0 && (
                 <div>
                    <h3 className="text-sm font-bold uppercase border-b border-black mb-3 pb-0.5">{activeCvLabels.additional}</h3>
                    <div className="text-sm">
                        <p><span className="font-bold">{activeCvLabels.driving} </span> {cvData.additionalInfo.drivingPermits.join(', ')}</p>
                    </div>
                 </div>
            )}

          </div>
          
          <TraviitFooter />
      </div>
    );
};

export const TemplateCreative: React.FC<CVTemplateProps> = ({ cvData, t }) => {
    const activeCvLabels = getLabels(cvData.documentLanguage, t);
    const isRtl = cvData.documentLanguage === 'ar';
  
    return (
      <div 
          id="cv-document" 
          dir={isRtl ? 'rtl' : 'ltr'}
          className={`bg-white text-gray-800 mx-auto w-[210mm] h-[297mm] relative flex ${isRtl ? 'font-cairo' : 'font-sans'} shadow-2xl overflow-hidden`}
      >
          {/* Sidebar */}
          <div className="w-1/3 bg-slate-900 text-white p-8 flex flex-col gap-8">
              <div className="text-center">
                  <div className="w-32 h-32 bg-white/10 rounded-full mx-auto mb-4 flex items-center justify-center text-4xl font-bold text-white border-4 border-white/20">
                      {cvData.personalInfo.firstName.charAt(0)}{cvData.personalInfo.lastName.charAt(0)}
                  </div>
                  <h1 className="text-2xl font-bold uppercase leading-tight mb-2">{cvData.personalInfo.firstName} <br/> {cvData.personalInfo.lastName}</h1>
                  <p className="text-blue-300 text-sm font-medium uppercase tracking-widest">{cvData.targetJob.title}</p>
              </div>
  
              <div>
                  <h3 className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-4 border-b border-slate-700 pb-2">Contact</h3>
                  <ul className="text-sm space-y-3 text-slate-300">
                      <li className="break-words">{cvData.personalInfo.email}</li>
                      <li dir="ltr">{cvData.personalInfo.phoneNumber}</li>
                      <li>{cvData.personalInfo.address.city}, {cvData.personalInfo.address.country}</li>
                  </ul>
              </div>
  
              <div>
                  <h3 className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-4 border-b border-slate-700 pb-2">{activeCvLabels.skills}</h3>
                  <div className="flex flex-wrap gap-2">
                      {cvData.skills.hardSkills.map(s => (
                          <span key={s} className="bg-slate-800 px-2 py-1 rounded text-xs text-slate-200">{s}</span>
                      ))}
                  </div>
              </div>

              <div>
                  <h3 className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-4 border-b border-slate-700 pb-2">{activeCvLabels.lang}</h3>
                  <ul className="text-sm space-y-2 text-slate-300">
                      {cvData.languages.map(l => (
                          <li key={l.language} className="flex justify-between">
                              <span>{l.language}</span>
                              <span className="text-slate-500 text-xs">{l.level}</span>
                          </li>
                      ))}
                  </ul>
              </div>
          </div>
  
          {/* Main Content */}
          <div className="w-2/3 p-10 bg-white">
              {(cvData.personalInfo.aboutMe) && (
                  <div className="mb-8">
                      <h3 className="text-lg font-bold text-slate-900 uppercase tracking-wider mb-3 flex items-center gap-2">
                          <span className="w-2 h-2 bg-blue-500 rounded-full"></span>
                          {activeCvLabels.summary}
                      </h3>
                      <p className="text-sm text-slate-600 leading-relaxed">{cvData.personalInfo.aboutMe}</p>
                  </div>
              )}
  
              <div className="mb-8">
                  <h3 className="text-lg font-bold text-slate-900 uppercase tracking-wider mb-6 flex items-center gap-2">
                      <span className="w-2 h-2 bg-blue-500 rounded-full"></span>
                      {activeCvLabels.exp}
                  </h3>
                  <div className="relative border-l-2 border-slate-100 ml-1 space-y-8 pl-6">
                      {cvData.professionalExperiences.map((exp, i) => (
                          <div key={i} className="relative">
                              <span className="absolute -left-[31px] top-1 w-3 h-3 bg-white border-2 border-blue-500 rounded-full"></span>
                              <h4 className="text-base font-bold text-slate-900">{exp.jobTitle}</h4>
                              <div className="text-xs font-bold text-blue-600 uppercase tracking-wide mb-2">
                                  {exp.companyName} | <span dir="ltr">{exp.period.start} - {exp.period.isCurrent ? (isRtl ? 'حاضر' : 'Present') : exp.period.end}</span>
                              </div>
                              <p className="text-sm text-slate-600 leading-relaxed">
                                  {exp.keyAchievements[0]} 
                              </p>
                          </div>
                      ))}
                  </div>
              </div>
  
              <div>
                  <h3 className="text-lg font-bold text-slate-900 uppercase tracking-wider mb-6 flex items-center gap-2">
                      <span className="w-2 h-2 bg-blue-500 rounded-full"></span>
                      {activeCvLabels.edu}
                  </h3>
                  <div className="space-y-4">
                      {cvData.education.map((edu, i) => (
                          <div key={i} className="bg-slate-50 p-4 rounded-lg">
                              <h4 className="font-bold text-slate-900">{edu.qualification}</h4>
                              <div className="text-sm text-slate-600">{edu.institution}</div>
                              <div className="text-xs text-slate-400 mt-1">{edu.graduationYear}</div>
                          </div>
                      ))}
                  </div>
              </div>
          </div>
          <TraviitFooter />
      </div>
    );
};
